### ISSUE TITLE
data is never defined

### ISSUE THREAD

**Issue by YashKumarVerma** [camicroscope/Caracal#116]
https://github.com/camicroscope/Caracal/blob/91fec6d581a2e54e85faeb053511c2df55b49053/handlers/authHandlers.js#L152-L156

**Comment by birm** [comment]
Data is x, the result of the user function, right?

**Comment by YashKumarVerma** [comment]
yep that's the value it takes, but the variable itself is never defined with var/let/const.

Just documenting the fixes that I'll be pushing in the PR

**Comment by Inkster6868** [comment]
hey is this issue still open? if yes, please assign this to me

**Comment by birm** [comment]
I think the fix to this is just to change line 152 from `data = x;` to `let data = x;`.
If you want to submit that as a PR, please do so from and against the 'develop' branch.

**Comment by VishalMyla** [comment]
Please Assign this issue to me

**Comment by birm** [comment]
This was fixed in  #153
