### ISSUE TITLE
Filter restrictions to apply to updates and deletes

### ISSUE THREAD

**Issue by birm** [camicroscope/Caracal#15]
depends on #14
Before performing a delete or update, check if the performing user has the correct userFilter entry.

**Comment by mgautam98** [comment]
Currently, a user can delete with get requests also. After finishing this issue, i.e to check authorization before delete, update still they can be tricked if they [CLICKHERE](http://localhost:4010/data/Slide/delete?_id=slideID). 
I guess we need to change the required routes to app.delete ^& app.update
