### ISSUE TITLE
"mongo: command not found" while running setup.py

### ISSUE THREAD

**Issue by Rahuljagwani** [camicroscope/Caracal#168]
@birm 

**Describe the bug**
Since after mongodb version 6.0+, `mongo` command is replaced by `mongosh`. Therefore while running `setup_script.sh`, the `mongo` command in systems(with mongodb v-6.0 and above) is not found.

**To Reproduce**
Just run `setup_script.sh`

**Possible Solution**
Either mention this in the documentation or modify `setup_script.sh` to check for both `mongo` and `mongosh`. I built the script with `mongosh` in my local setup, and everything was fine.

**Comment by birm** [comment]
Thanks for the report, fixed with #169
