### ISSUE TITLE
Error while trying to use tfjs-node libraries in node.

### ISSUE THREAD

**Issue by akhil-rana** [camicroscope/Caracal#44]
**Error while trying to use [tfjs-node](https://github.com/tensorflow/tfjs/tree/master/tfjs-node) libraries in node.**

1. Include `"@tensorflow/tfjs-node": "^2.0.1"` into package.json
2. Rebuild caracal (back) image using docker-compose
3. Run caMicroscope using `up` command

**Logs**

![DeepinScreenshot_select-area_20200716064916](https://user-images.githubusercontent.com/36575628/87615492-814ebc80-c730-11ea-9787-eb2a063840d6.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (Deepin)

**Additional context**

- Issue seems to be with alpine image in docker. 
- I tried installing `libc6-compat` in alpine but it didn't seem to help.
- Changing image to stretch-slim fixes the issue for now. Looking for other solutions too.

**Comment by birm** [comment]
relates to https://github.com/tensorflow/tfjs/issues/1425

**Comment by akhil-rana** [comment]
Should we close this?

Resolved by using `node:14-stretch-slim`  in #47
