### ISSUE TITLE
tfjs install err on osx

### ISSUE THREAD

**Issue by birm** [camicroscope/Caracal#49]
building develop.yml on osx returns:
```
Step 6/11 : RUN npm install
 ---> Running in 20c5e97fea74
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /root/src/node_modules/@tensorflow/tfjs/dist/tools/custom_bundle/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/root/src/node_modules/@tensorflow/tfjs/dist/tools/custom_bundle/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-14T00_33_08_704Z-debug.log
ERROR: Service 'back' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 254
```

I'm away now, so I don't know if this is os specific.

**Comment by birm** [comment]
looks universal; xenial is complaining too https://travis-ci.org/github/camicroscope/Caracal/jobs/717769307

**Comment by birm** [comment]
<img width="791" alt="Screen Shot 2020-08-13 at 9 02 44 PM" src="https://user-images.githubusercontent.com/4951803/90205851-6495bb00-dda8-11ea-9cb7-5d7160a7d4ca.png">

The plot thickens

**Comment by birm** [comment]
Temporarily resolved by avoiding 2.2.0 in 20a75e65ed21e9d8d2074247ce11c154c3c8b83e; leaving open until we have a fixed npm release, or another solution (e.g. another package manager)

**Comment by akhil-rana** [comment]
v2.3.0 has been released.
We should try that.

**Comment by birm** [comment]
Seems to work! e7b801d358d02709ad9240cfca572ae39d8af373
