### ISSUE TITLE
Precalculating and Caching some mongo results

### ISSUE THREAD

**Issue by birm** [camicroscope/Caracal#67]
Some mongo results take a long time to fetch, don't change often, and don't have much data. We could add in a cache/no-cache case to precalculate results, especially Distinct operations. Inspired by slow calls to get segmentation data.

**Comment by ayan-biswas0412** [comment]
@birm can you ellaborate on this topic ? it seems interesting I would love to work in this

**Comment by birm** [comment]
I'm no longer convinced that this is necessary, due in part to some ui wizardry.
