### ISSUE TITLE
use dotenv to handle environment variables

### ISSUE THREAD

**Issue by YashKumarVerma** [camicroscope/Caracal#74]
**Is your feature request related to a problem? Please describe.**
by using a .env file, we can handle & document environment variables in a better manner as 
- no need to pass as cli option
- can be used while running scripts
- can be grouped and used in batches

**Describe the solution you'd like**
- using a library like [dotenv](http://npmjs.com/package/dotenv) which uses a `.env` file.
- (also?) a `.env.example` file with all possible configuration options that are possible via environment variables.

**Describe alternatives you've considered**
- yaml based configs can also be used.

**Additional context**

willing to work on it

**Comment by birm** [comment]
I would recommend considering caracal in the context which camicroscope usually deploys it: https://github.com/camicroscope/Distro

That said, as long as there's no confusion, I'm happy to let caracal support .env files too.

**Comment by YashKumarVerma** [comment]
> I would recommend considering caracal in the context which camicroscope usually deploys it: [camicroscope/Distro](https://github.com/camicroscope/Distro)
> 
> That said, as long as there's no confusion, I'm happy to let caracal support .env files too.

please correct me if I'm wrong, I'm learning a lot of new things here. So this repository (Caracal) is used by `Distro` to build a new image.

and implementing dotenv in this repo is fine right?

**Comment by birm** [comment]
Yes, I should have been more clear. I was just saying that I find it easier to use a compose script to pass env vars where possible. But, this isn't necessarily bound to caMicroscope, so I do think this is a good proposal.

**Comment by YashKumarVerma** [comment]
thanks for the assistance!
