### ISSUE TITLE
Application does not terminate if database connection fails

### ISSUE THREAD

**Issue by YashKumarVerma** [camicroscope/Caracal#82]
**Describe the bug**
- since various components of the application depend on a mongodb database, it **should terminate** if the connection is not made.

**To Reproduce**
1. kill your MongoDB instance
2. try running the system

**Expected behavior**
1. since MongoDB is a hard dependency of the project, it must terminate if connection is not made.

**Screenshots**
[![asciicast](https://asciinema.org/a/401523.svg)](https://asciinema.org/a/401523)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04

**Comment by birm** [comment]
good point!

**Comment by YashKumarVerma** [comment]
while diving into the codebase, I've observed that each of the database calls is creating a new connection instead of using the existing one (pooling them).

Could we somehow improve it by using one definition and then re-using it across the application? This will also allow us to leverage the features of pooling.

@birm

**Comment by birm** [comment]
closed with #90
