### ISSUE TITLE
mocha not in dependency list 

### ISSUE THREAD

**Issue by YashKumarVerma** [camicroscope/Caracal#87]
**Describe the bug**
- the project uses mocha for testing the components but does not have mocha in the dependency list.

**To Reproduce**
- quickly glance through package.json and test script

**Expected behavior**
- all dependencies should be listed in package.json

**Screenshots**
- NA

**Comment by birm** [comment]
added in https://github.com/camicroscope/Caracal/commit/f188b5648dd4b8d92f1e07026c13adfae987ac30
