### ISSUE TITLE
Bugs related to accessing undefined values in dev-backup branch

### ISSUE THREAD

**Issue by siddhanth339** [camicroscope/Caracal#96]
**Describe the bug**
When I run the application using docker-compose with Caracal (develop branch), caMicroscope, and Distro repos, I get errors based on accessing undefined values from the /Caracal/service/database/connector.js and the /Caracal/handlers/dataTransformationHandler.js files

**To Reproduce**
1. Run `docker-compose -f develop.yml build`
2. Then, run `docker-compose -f develop.yml up`
3. See the errors

**Expected behavior**
Run the application smoothly without any errors.

**Screenshots**

![error-undefined](https://user-images.githubusercontent.com/40331239/116446247-6212bd00-a874-11eb-8dfe-8ad976f71e18.png)

![lengthUndefined](https://user-images.githubusercontent.com/40331239/116446278-6939cb00-a874-11eb-83a7-25e965e3e682.png)

**System Information:**

> Device: LENOVO_MT_81DE_BU_idea_FM_ideapad 330-15IKB
> Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, 1800 Mhz, 4 Core(s), 8 Logical Processor(s)
> OS: Microsoft Windows 10 Home
> Browser: Chrome
> Version: 10.0.19041 Build 19041

**Additional context**
I suspect that these errors are due to lots of callback functions. The values of variables are being accessed outside the callback functions which are asynchronous, this being the main cause.
Files to look into:

-  /Caracal/service/database/connector.js 
-  /Caracal/service/database/index.js 
- /Caracal/handlers/dataTransformationHandler.js files

**Comment by birm** [comment]
Does the master branch of caracal build ok?

**Comment by siddhanth339** [comment]
Yes

**Comment by siddhanth339** [comment]
Problem is with the develop branch

**Comment by YashKumarVerma** [comment]
for anyone who's following this: the code for the said issue is in `dev-backup` branch

**Comment by YashKumarVerma** [comment]
@Brim were you able to reproduce anything similar during the time of #90 ? Strange that I did not face this issue, I'll try doing a fresh setup and let you know what I find.

**Comment by YashKumarVerma** [comment]
update: I was able to reproduce the issue on a fresh setup

**Comment by YashKumarVerma** [comment]
I believe this can be closed now.
